---

- hosts: all
  become: true
  pre_tasks:

  - name: Updates Cache (RedHat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: Updates Cache (Debian & Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == ["Debian", "Ubuntu"]


- hosts: all
  become: true
  tasks:
  
  - name: create ansible user
    tags: always
    user:
      name: ansible
      groups: root
      
  - name: applying ssh key for ansible usr
    tags: always
    authorized_key:
      user: ansible
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+aiivdyBrrrTAvrzTG0cPxQW68IpZR+OlBf8vBlj7K Ansible"
      
  - name: add ansible usr to sudoers file
    tags: always
    copy: 
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440
    
    
