---

- hosts: all
  become: true
  pre_tasks:

  - name: Updates Cache (RedHat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: Updates Cache (Debian & Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == ["Debian", "Ubuntu"]


- hosts: all
  become: true
  tasks:
  
  - name: add ssh key for ansible usr
    tags: always
    authorized_key:
      user: ansible
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+aiivdyBrrrTAvrzTG0cPxQW68IpZR+OlBf8vBlj7K Ansible"
