---

- hosts: rhel_servers
  become: true
  pre_tasks:

  - name: Updates Cache (RedHat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

- hosts: rhel_servers
  become: true
  tasks:

  - name: install apache & php packages for RedHat
    tags: apache,httpd,php,rhel
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: start httpd
    tags: httpd,apache,start_service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"
