---

- hosts: all
  become: true
  pre_tasks:

  - name: Updates Cache (RedHat)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"

  - name: Updates Cache (Debian & Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == ["Debian", "Ubuntu"]


- hosts: ubuntu_servers
  become: true
  tasks:
  
  - name: install apache2 & php packages for ubuntu
    tags: apache,apache2,php,ubuntu,debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: rhel_servers
  become: true
  tasks:

  - name: install apache & php packages for RedHat
    tags: apache,httpd,php,rhel
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"
    
- hosts: debian_servers
  become: true
  tasks:
  
  - name: install pluma gui text editor, ahache & php support 
    tags: pluma,gui_text_editor,debian,apache,apache2,php
    apt:
      name: 
        - pluma
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"
