---

- hosts: all
  become: true
  pre_tasks:

  - name: Updates Cache (RedHat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: Updates Cache (Debian & Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == ["Debian", "Ubuntu"]


- hosts: all
  become: true
  tasks:
  
  - name: install unzip
    tags: unzip
    package:
      name: unzip
      state: latest

  - name: install terraform
    tags: terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.4/terraform_1.6.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0775
      owner: root
      group: root


