- name: install apache2 & php packages for ubuntu
  tags: apache,apache2,php,ubuntu,debian
  apt:
   name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == ["Ubuntu", "Debian"]

- name: install apache & php packages for RedHat
  tags: apache,httpd,php,rhel
  yum:
    name: 
      - httpd
      - php
    state: latest
  when: ansible_distribution == "RedHat"

- name: start httpd
  tags: httpd,apache,start_service
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"
  
- name: transfer default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
